name: finalfyp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.0
  dialog_flowtter: ^0.3.3
  flutter_local_notifications: ^19.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.1
  http: ^0.13.6
  path_provider: ^2.1.2
  intl: 0.19.0
  pdf: ^3.11.3
  permission_handler: ^11.4.0
  open_file: ^3.5.10
  flutter_pdfview: ^1.4.0
  firebase_messaging: ^15.2.5
  file_picker: ^9.2.2
  flutter_launcher_icons: ^0.14.3
  timeago: ^3.7.0




  share_plus: ^10.1.4

  printing: ^5.14.2
  device_info_plus: ^11.3.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "Asset/images/logo.jpeg"



dependency_overrides:
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  carousel_slider: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Asset/images/
    - Asset/dialog_flow_auth.json

  fonts:
    - family: Poppins
      fonts:
        - asset: Asset/Customfont/Poppins-Black.ttf
    - family: Poppinsthin
      fonts:
        - asset: Asset/Customfont/Poppins-Bold.ttf
    - family: Poppinsregular
      fonts:
        - asset: Asset/Customfont/Poppins-Regular.ttf
    - family: Poppinsmedium
      fonts:
        - asset: Asset/Customfont/Poppins-Medium.ttf
