// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6uMyOCdfb29aonR-jajS5eKTdLZ-nRdM',
    appId: '1:263945902753:web:a1bec24e671cfc86f76ee0',
    messagingSenderId: '263945902753',
    projectId: 'fyproject-b3aa0',
    authDomain: 'fyproject-b3aa0.firebaseapp.com',
    storageBucket: 'fyproject-b3aa0.firebasestorage.app',
    measurementId: 'G-VDDJRH1K0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOb6pHth7ceHak_xL_Ixs6SN7-CSqihbA',
    appId: '1:263945902753:android:d3b23e80a9e994adf76ee0',
    messagingSenderId: '263945902753',
    projectId: 'fyproject-b3aa0',
    storageBucket: 'fyproject-b3aa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoIJb5gUzcvz5TjANHfPGM3baO9czQpaE',
    appId: '1:263945902753:ios:1c046f33498e2791f76ee0',
    messagingSenderId: '263945902753',
    projectId: 'fyproject-b3aa0',
    storageBucket: 'fyproject-b3aa0.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoIJb5gUzcvz5TjANHfPGM3baO9czQpaE',
    appId: '1:263945902753:ios:1c046f33498e2791f76ee0',
    messagingSenderId: '263945902753',
    projectId: 'fyproject-b3aa0',
    storageBucket: 'fyproject-b3aa0.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6uMyOCdfb29aonR-jajS5eKTdLZ-nRdM',
    appId: '1:263945902753:web:a5e12634a2c46cf7f76ee0',
    messagingSenderId: '263945902753',
    projectId: 'fyproject-b3aa0',
    authDomain: 'fyproject-b3aa0.firebaseapp.com',
    storageBucket: 'fyproject-b3aa0.firebasestorage.app',
    measurementId: 'G-3FX5JYNXNG',
  );
}
